### ISSUE TITLE
[Broken] on 1.8.7, The default OSX Ruby in Mountain Lion 

### ISSUE THREAD

**Issue by loadedsith** [asilano/succubus#2]
I've been able to get succubus to run, but when i run the default examples it returns null. I assume this is not a big deal, as upgrading is easy, but if you can take a look at what I've done and spot what I'm missing, it might be worth the time. 

[https://github.com/loadedsith/succubus](https://github.com/loadedsith/succubus)

I made my changes to grammar.rb because of [this stackoverflow question](http://stackoverflow.com/questions/3026943/define-method-for-instance-of-class)

I've tried to verify my changes to generator.rb on rubular.com, as evidenced in the screen shots.
![screen shot 2013-07-18 at 10 57 11 pm](https://f.cloud.github.com/assets/1950785/823928/28b08f9e-f029-11e2-925d-d1c2151def38.png)
![screen shot 2013-07-18 at 10 57 05 pm](https://f.cloud.github.com/assets/1950785/823929/28bcab80-f029-11e2-9943-ab892fe52f14.png)

Thanks for making the version that works on 2!

**Comment by asilano** [comment]
The problem appears to be that you've switched `scan` for `match` in `Generator#invoke`. 

A match found by `scan` produces an array of the matched groups, so `match[0]` is the first matched group. A match found by `match`, on the other hand, is an instance of `class MatchData`, which defines `[]` such that `[0]` is the whole text matched, and `[1]` is the first group etc.

**Comment by asilano** [comment]
@loadedsith - I've pushed a new branch which takes a different approach with the regex - it checks for the backslashes in two steps, first matching any `<foo>` group with any number of backslashes, and then branching dependent on whether that number is odd or even.

Can you check it out and let me know if everything works for you now?

**Comment by loadedsith** [comment]
It is good enough for my useage, but doesn't behave as expected:

This is my test:

```
 #!/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby -rubygems -wKU
 gem 'succubus'
 require 'succubus'
 grammar = Succubus::Grammar.new do
   add_rule :base, "\\<colour> I have a \\<noun> <colour> <pet>"
   add_rule :base2, "\<colour> I have a \<noun> <colour> <pet>"
   add_rule :noun, "running", "sleeping"
   add_rule :colour, "black", "brown", "white"
   add_rule :pet, "cat", "dog", "rabbit"
 end
 puts grammar.execute :base
 puts grammar.execute :base2 
```

and this is what i get back:

```
/Library/Ruby/Gems/1.8/gems/succubus-0.1.0/lib/succubus/grammar.rb:27: warning: `&' interpreted as argument prefix
<colour> I have a <noun> black dog
white I have a sleeping brown dog
```

The warning is easily fixed:

```
grammar.rb
27:      instance_eval(&block)
```

I'm not experienced enough with Ruby to know how to run the built in test, but if you tell me know I can get that done for you.

**Comment by asilano** [comment]
Thanks for spotting the warning, I'll fix that up.

As for your test Grammar, remember that backslashes are escape characters in normal Ruby too :) - that is, the string `"\\<colour>"` consists of a _single_ backslash before the `<colour>` group.

Assuming you've grabbed the whole repo, I think you should be able to run the tests be calling `rake install`, then `rake` from the repo's base directory.

**Comment by asilano** [comment]
Assuming I _ever_ get back to this, I won't be targeting Ruby 1.8.x!
